'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createSellerProduct } from '@/app/actions/marketplace'

export function ProductForm() {
  const router = useRouter()
  const [error, setError] = useState('')
  const [pending, setPending] = useState(false)
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(''); setPending(true)
    const form = new FormData(event.currentTarget)
    try { await createSellerProduct({ name: String(form.get('name')), slug: String(form.get('slug')), category: String(form.get('category')), description: String(form.get('description')), quantity: Number(form.get('quantity')), unit: String(form.get('unit')), price: Number(form.get('price')), mineralContent: String(form.get('mineralContent')), grade: String(form.get('grade')), country: String(form.get('country')), region: String(form.get('region')), sellerName: String(form.get('sellerName')), sellerCompany: String(form.get('sellerCompany')) }); router.push('/dashboard/seller') } catch { setError('We could not save this listing. Check the details and try again.') } finally { setPending(false) }
  }
  return <form onSubmit={submit} className="mt-10 flex flex-col gap-8"><section className="rounded-2xl border border-white/10 bg-ink p-6 md:p-8"><h2 className="font-display text-2xl">Core listing details</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{[['name','Product name','Premium Ilmenite Sand'],['slug','URL slug','premium-ilmenite-sand'],['category','Category','Black Sand'],['mineralContent','Mineral content','Titanium, iron, vanadium'],['grade','Grade / specification','TiO₂ 54%+'],['country','Country of origin','Mozambique'],['region','Origin region','Nampula'],['quantity','Available quantity','2500'],['unit','Unit','MT'],['price','Indicative price per unit','0']].map(([name,label,placeholder]) => <label key={name} className="flex flex-col gap-2 text-sm text-sand/65">{label}<input required={['name','slug','description','quantity','mineralContent','grade','country','sellerCompany'].includes(name)} name={name} placeholder={placeholder} type={['quantity','price'].includes(name) ? 'number' : 'text'} className="rounded-xl border border-white/10 bg-charcoal px-4 py-3 text-base text-sand outline-none focus:border-mineral" /></label>)}</div><label className="mt-5 flex flex-col gap-2 text-sm text-sand/65">Description<textarea required name="description" rows={5} placeholder="Describe quality, processing, packaging, and buyer use cases" className="rounded-xl border border-white/10 bg-charcoal px-4 py-3 text-base text-sand outline-none focus:border-mineral" /></label></section><section className="rounded-2xl border border-white/10 bg-ink p-6 md:p-8"><h2 className="font-display text-2xl">Seller identity</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="flex flex-col gap-2 text-sm text-sand/65">Contact name<input required name="sellerName" placeholder="Your name" className="rounded-xl border border-white/10 bg-charcoal px-4 py-3 text-base text-sand outline-none focus:border-mineral" /></label><label className="flex flex-col gap-2 text-sm text-sand/65">Company name<input required name="sellerCompany" placeholder="Registered company" className="rounded-xl border border-white/10 bg-charcoal px-4 py-3 text-base text-sand outline-none focus:border-mineral" /></label></div></section>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}<button disabled={pending} className="rounded-xl bg-mineral px-6 py-4 text-base font-semibold text-charcoal disabled:opacity-50">{pending ? 'Saving listing…' : 'Publish listing'}</button></form>
}
