import Link from 'next/link'
import { ArrowRight, BookOpen, CalendarDays } from 'lucide-react'

const insights = [
  { category: 'Market intelligence', title: 'What buyers should verify before sourcing a new mineral supplier', excerpt: 'A practical checklist for evaluating documentation, specifications, and commercial readiness before the first conversation.', date: 'June 18, 2026', read: '6 min read' },
  { category: 'Materials guide', title: 'How to compare mineral grades without getting lost in the numbers', excerpt: 'The key specifications that matter when you are comparing supply across regions, labs, and applications.', date: 'May 29, 2026', read: '8 min read' },
  { category: 'Trade notes', title: 'Why transparent origin data changes the sourcing conversation', excerpt: 'Traceability is more than a checkbox. It gives serious teams the context they need to make better buying decisions.', date: 'May 10, 2026', read: '5 min read' },
]

function Header() {
  return <header className="border-b border-white/10 bg-charcoal/95 px-6 backdrop-blur md:px-10"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Black Sand home"><span className="grid size-9 place-items-center rounded-full bg-mineral text-charcoal"><span className="text-lg font-semibold">B</span></span><span className="font-display text-lg font-semibold tracking-[0.18em]">BLACK SAND</span></Link><nav className="flex items-center gap-5 text-sm text-sand/65 md:gap-8"><Link href="/marketplace" className="hover:text-sand">Marketplace</Link><Link href="/about" className="hover:text-sand">How it works</Link><Link href="/blog" className="text-sand">Insights</Link><Link href="/dashboard/buyer" className="rounded-full bg-mineral px-4 py-2 font-medium text-charcoal hover:bg-mineral-light">Sign in</Link></nav></div></header>
}

export default function BlogPage() {
  return <main className="min-h-screen bg-charcoal text-sand"><div className="border-b border-white/10 bg-charcoal px-6 py-2 text-center text-xs tracking-wide text-sand/65">Trade with confidence. Every seller is verified before they list.</div><Header /><section className="border-b border-white/10 px-6 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><p className="mb-6 flex items-center gap-3 text-xs font-medium uppercase tracking-[0.24em] text-mineral"><BookOpen className="size-4" aria-hidden="true" /> Black Sand insights</p><h1 className="max-w-4xl font-display text-5xl leading-[1.04] tracking-[-0.045em] md:text-7xl">Better context for the materials market.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-sand/65">Practical notes on mineral sourcing, supplier verification, and the decisions that make global trade easier to navigate.</p></div></section><section className="mx-auto max-w-7xl px-6 py-20 md:px-10 md:py-28"><div className="grid gap-6 lg:grid-cols-3">{insights.map((item) => <article key={item.title} className="flex flex-col border-t border-mineral pt-6"><p className="text-xs font-medium uppercase tracking-[0.18em] text-mineral">{item.category}</p><h2 className="mt-7 font-display text-2xl leading-tight tracking-[-0.025em]">{item.title}</h2><p className="mt-4 flex-1 leading-7 text-sand/55">{item.excerpt}</p><div className="mt-8 flex items-center justify-between border-t border-white/10 pt-4 text-xs text-sand/40"><span className="flex items-center gap-2"><CalendarDays className="size-4" aria-hidden="true" /> {item.date}</span><span>{item.read}</span></div><Link href={`/blog/${encodeURIComponent(item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''))}`} className="mt-5 inline-flex items-center self-start text-sm text-sand/75 hover:text-mineral">Read insight <ArrowRight className="ml-2 size-4" aria-hidden="true" /></Link></article>)}</div></section><section className="border-y border-white/10 bg-ink px-6 py-20 md:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="text-xs uppercase tracking-[0.2em] text-mineral">Explore the supply</p><h2 className="mt-4 max-w-xl font-display text-4xl tracking-[-0.035em] md:text-5xl">Put insight into motion.</h2></div><Link href="/marketplace" className="inline-flex items-center rounded-full bg-mineral px-6 py-4 text-sm font-medium text-charcoal hover:bg-mineral-light">Explore marketplace <ArrowRight className="ml-2 size-4" /></Link></div></section><footer className="border-t border-white/10 px-6 py-10 md:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between text-sm text-sand/45"><Link href="/" className="font-display tracking-[0.18em] text-sand/75">BLACK SAND</Link><span>© 2026 Black Sand Exchange</span></div></footer></main>
}
