'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowUpDown, Check, ChevronDown, Filter, Heart, MapPin, Search, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { demoProducts } from '@/lib/domain'

const extraProducts = [
  { id: 'p-003', slug: 'magnetite-black-sand', name: 'Magnetite Black Sand', origin: 'Indonesia', grade: 'Fe₃O₄ 68%+', quantity: 4600, unit: 'MT', seller: 'Pacific Ore Co.', verified: true, category: 'Magnetite', price: '$88–104' },
  { id: 'p-004', slug: 'titanium-rich-sand', name: 'Titanium-Rich Black Sand', origin: 'South Africa', grade: 'TiO₂ 61%+', quantity: 1200, unit: 'MT', seller: 'Cape Mineral Works', verified: true, category: 'Ilmenite', price: '$142–158' },
  { id: 'p-005', slug: 'volcanic-iron-sand', name: 'Volcanic Iron Sand', origin: 'Japan', grade: 'Fe 57%+', quantity: 780, unit: 'MT', seller: 'Kuro Resources', verified: false, category: 'Iron sand', price: '$96–110' },
]

const products = [...demoProducts.map((product) => ({ ...product, seller: product.sellerId === 'seller-001' ? 'Nacala Minerals' : 'Atlas Carbon', category: product.name.includes('Ilmenite') ? 'Ilmenite' : 'Graphite', price: product.name.includes('Ilmenite') ? '$118–132' : '$210–240' })), ...extraProducts]

function Logo() {
  return <Link href="/" className="flex items-center gap-3" aria-label="Black Sand home"><span className="grid size-9 place-items-center rounded-full bg-mineral text-charcoal"><span className="text-lg font-semibold">B</span></span><span className="font-display text-lg font-semibold tracking-[0.18em]">BLACK SAND</span></Link>
}

export default function MarketplacePage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All types')
  const [verifiedOnly, setVerifiedOnly] = useState(false)
  const [favorites, setFavorites] = useState<string[]>([])
  const [sort, setSort] = useState('Newest')

  const filtered = useMemo(() => {
    const result = products.filter((product) => {
      const matchesQuery = `${product.name} ${product.origin} ${product.grade} ${product.seller}`.toLowerCase().includes(query.toLowerCase())
      const matchesCategory = category === 'All types' || product.category === category
      return matchesQuery && matchesCategory && (!verifiedOnly || product.verified)
    })
    return [...result].sort((a, b) => sort === 'Quantity' ? b.quantity - a.quantity : sort === 'Price' ? a.price.localeCompare(b.price) : 0)
  }, [category, query, sort, verifiedOnly])

  return <main className="min-h-screen bg-charcoal text-sand">
    <div className="border-b border-white/10 px-6 py-2 text-center text-xs tracking-wide text-sand/60">Trade with confidence. Every seller is reviewed before they list.</div>
    <header className="border-b border-white/10 bg-charcoal/95 px-6 backdrop-blur md:px-10"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between"><Logo /><nav className="hidden items-center gap-8 text-sm text-sand/65 md:flex"><Link className="text-sand" href="/marketplace">Marketplace</Link><Link href="/about">How it works</Link><Link href="/blog">Insights</Link><Link href="/contact">Contact</Link></nav><div className="flex items-center gap-4"><Link className="hidden text-sm text-sand/70 hover:text-sand sm:block" href="/sign-in">Sign in</Link><Link className="rounded-full bg-mineral px-4 py-2.5 text-sm font-medium text-charcoal transition hover:bg-mineral-light" href="/dashboard/seller">List supply</Link></div></div></header>

    <section className="border-b border-white/10 bg-ink px-6 py-16 md:px-10"><div className="mx-auto max-w-7xl"><Link href="/" className="text-sm text-sand/50 hover:text-mineral"><ArrowLeft className="mr-2 inline size-4" /> Back home</Link><div className="mt-12 flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs uppercase tracking-[0.24em] text-mineral">The catalog</p><h1 className="mt-4 max-w-2xl font-display text-5xl leading-[1.05] tracking-[-0.04em] md:text-7xl">Find the right black sand.</h1><p className="mt-5 max-w-xl leading-7 text-sand/60">Compare verified supply, technical grades, and available volumes from serious mineral suppliers.</p></div><div className="flex items-center gap-3 text-sm text-sand/55"><span className="grid size-10 place-items-center rounded-full border border-mineral/30 bg-mineral/10 text-mineral"><ShieldCheck /></span><span>Verified supply<br /><strong className="font-normal text-sand">Reviewed listings</strong></span></div></div></div></section>

    <section className="mx-auto max-w-7xl px-6 py-10 md:px-10"><div className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-ink p-4 md:flex-row md:items-center"><div className="flex flex-1 items-center gap-3 rounded-xl border border-white/10 px-4 py-3"><Search className="size-5 text-mineral" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products, origins, grades, or sellers" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-sand/35" /></div><div className="flex flex-wrap gap-3"><label className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-3 text-sm text-sand/70"><Filter className="size-4 text-mineral" /><select value={category} onChange={(event) => setCategory(event.target.value)} className="bg-transparent outline-none"><option className="bg-ink">All types</option><option className="bg-ink">Ilmenite</option><option className="bg-ink">Magnetite</option><option className="bg-ink">Iron sand</option><option className="bg-ink">Graphite</option></select></label><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-white/10 px-3 py-3 text-sm text-sand/70"><input type="checkbox" checked={verifiedOnly} onChange={(event) => setVerifiedOnly(event.target.checked)} className="accent-[var(--mineral)]" /> Verified only</label><label className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-3 text-sm text-sand/70"><ArrowUpDown className="size-4 text-mineral" /><select value={sort} onChange={(event) => setSort(event.target.value)} className="bg-transparent outline-none"><option className="bg-ink">Newest</option><option className="bg-ink">Quantity</option><option className="bg-ink">Price</option></select></label></div></div><div className="mt-8 flex items-center justify-between"><p className="text-sm text-sand/50"><span className="text-sand">{filtered.length}</span> listings matching your search</p><button className="flex items-center gap-2 text-sm text-sand/55 hover:text-sand"><SlidersHorizontal className="size-4" /> More filters <ChevronDown className="size-4" /></button></div></section>

    <section className="mx-auto grid max-w-7xl gap-5 px-6 pb-24 md:grid-cols-2 md:px-10 lg:grid-cols-3">{filtered.map((product) => <article key={product.id} className="group overflow-hidden rounded-2xl border border-white/10 bg-ink transition hover:-translate-y-1 hover:border-mineral/40"><div className="relative aspect-[1.3] overflow-hidden"><img src={'/mineral-hero.png'} alt={product.name} className="size-full object-cover opacity-75 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-transparent to-transparent" /><button onClick={() => setFavorites((current) => current.includes(product.id) ? current.filter((id) => id !== product.id) : [...current, product.id])} className="absolute right-4 top-4 grid size-9 place-items-center rounded-full border border-white/15 bg-charcoal/60 backdrop-blur" aria-label={`${favorites.includes(product.id) ? 'Remove' : 'Save'} ${product.name}`}><Heart className={favorites.includes(product.id) ? 'size-4 fill-mineral text-mineral' : 'size-4'} /></button><div className="absolute bottom-4 left-5 flex items-center gap-2 text-xs text-sand/75"><span className="rounded-full bg-mineral px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-charcoal">{product.verified ? 'Verified' : 'Reviewing'}</span><span>{product.origin}</span></div></div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-2xl">{product.name}</h2><p className="mt-2 text-sm text-sand/50">{product.seller}</p></div><Check className="mt-1 size-5 text-mineral" /></div><div className="mt-5 grid grid-cols-2 gap-4 border-y border-white/10 py-4 text-sm"><div><p className="text-xs text-sand/40">Mineral grade</p><p className="mt-1 text-sand/85">{product.grade}</p></div><div><p className="text-xs text-sand/40">Available</p><p className="mt-1 text-sand/85">{product.quantity.toLocaleString()} {product.unit}</p></div></div><div className="mt-5 flex items-center justify-between"><p><span className="text-xs text-sand/40">Indicative / MT</span><br /><span className="text-lg text-mineral">{product.price}</span></p><span className="flex items-center gap-1 text-xs text-sand/50"><MapPin className="size-3" /> {product.origin}</span></div><div className="mt-5 flex gap-3"><Link href={`/materials/${product.slug}`} className="flex-1 rounded-full border border-white/15 px-4 py-3 text-center text-sm transition hover:border-mineral hover:text-mineral">View details</Link><Link href="/dashboard/buyer" className="flex-1 rounded-full bg-mineral px-4 py-3 text-center text-sm font-medium text-charcoal transition hover:bg-mineral-light">Request quote</Link></div></div></article>)}</section>
    {filtered.length === 0 && <div className="mx-auto max-w-7xl px-6 pb-24 text-center md:px-10"><p className="font-display text-3xl">No listings found.</p><p className="mt-3 text-sand/50">Try a different search or remove a filter.</p></div>}
  </main>
}
